configfile: "config/config.yml"

SYSTEMS = ["GaSb",
           "ethanol",
           ]

rule all:
   input:
       expand("results/{label}_qpoint_phonon_modes.json", label=SYSTEMS),
       expand("results/{label}_abins.npz", label=SYSTEMS),
       expand("results/{label}_abins_raw.npz", label=SYSTEMS),
       expand("results/{label}_abins_{temperature}k_isotropic_raw.npz", label=SYSTEMS, temperature=[10, 100]),

rule phonon_to_json:
    """Convert CASTEP .phonon file to Euphonic JSON"""
    input:
        "data/{label}.phonon"
    output:
        "results/{label}_qpoint_phonon_modes.json"
    conda:
        "envs/mantid.yml"
    script:
        "scripts/phonon_to_json.py"

rule mlip_ethanol_opt:
    """Get optimised ethanol molecule using MLIP"""
    output:
        "results/ethanol-opt.traj",
        "results/ethanol-opt.extxyz",
    conda:
        "envs/mlip.yml"
    threads: 8
    params:
        calc_params=config["calc_params"]
    script:
        "scripts/opt_ethanol.py"

rule mlip_ethanol_phonon:
    """Get MLIP phonons from structure"""
    output:
        "results/{label}-phonopy.yaml",
        "results/{label}-force_constants.hdf5",
    input:
        "results/{label}-opt.extxyz",
    conda:
        "envs/mlip.yml"    
    threads: 8
    params:
        label=(lambda w: w["label"]),
        calc_params=config["calc_params"],
        displacement=1e-3,
    script:
        "scripts/mlip_phonons.py"

rule fc_to_json_modes:
    """Get QpointPhononModes JSON from force constants data"""
    output:
        "results/{label}_qpoint_phonon_modes.json"
    input:
        "results/{label}-phonopy.yaml",
        "results/{label}-force_constants.hdf5",        
    params:
        qpts=config["modes"]["qpts"],
        weights=config["modes"]["weights"],
    conda:
        "envs/mantid.yml"
    script:
        "scripts/phonopy_fc_modes.py"

abins_tosca_kwargs = {
    "Instrument": "TOSCA",
    "Setting": "Backward (TOSCA)",
}

rule abins_tosca:
    """Get Abins fundamental TOSCA spectrum with instrumental broadening"""
    output:
        "results/{label}_abins.npz"
    input:
        "results/{label}_qpoint_phonon_modes.json"
    conda:
        "envs/mantid.yml"
    params:
        raw=False,
        abins_kwargs=(abins_tosca_kwargs | config["abins_kwargs"]),
    script:
        "scripts/run_abins.py"

rule abins_tosca_raw:
    """Get Abins fundamental TOSCA spectrum without broadening"""
    output:
        "results/{label}_abins_raw.npz"
    input:
        "results/{label}_qpoint_phonon_modes.json"
    conda:
        "envs/mantid.yml"
    params:
        raw=True,
        abins_kwargs=(abins_tosca_kwargs | config["abins_kwargs"]),
    script:
        "scripts/run_abins.py"

rule abins_tosca_isotropic_raw:
    """Get fully-isotropic fundamental TOSCA spectrum without broadening"""
    output:
        "results/{label}_abins_{temperature}k_isotropic_raw.npz"
    input:
        "results/{label}_qpoint_phonon_modes.json"
    conda:
        "envs/mantid.yml"
    params:
        isotropic=True,
        raw=True,
        abins_kwargs=(lambda w: (
            abins_tosca_kwargs
            | config["abins_kwargs"]
            | {"TemperatureInKelvin": w["temperature"]})),
    script:
        "scripts/run_abins.py"
