name: Validation

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Target branch"
        required: true
        type: string
      json:
        description: "Include JSON in artifact"
        required: true
        type: boolean
        default: false
      commit:
        description: "Add/commit generated plots to branch"
        require: true
        type: boolean
        default: false

jobs:
  snakemake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}
          fetch-tags: true
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: dev/snakemake.yml
          miniforge-version: latest

      - name: "Run snakemake"
        shell: bash -l {0}
        run: |
          snakemake --directory dev/validation --snakefile dev/validation/workflow/Snakefile --sdm conda -c 4

      - name: "Save plot as artifact"
        if: ${{ ! inputs.json }}
        uses: actions/upload-artifact@v7
        with:
          name: Validation results
          path: 'dev/validation/results/*.png'

      - name: "Save all results as artifact"
        if: ${{ inputs.json }}
        uses: actions/upload-artifact@v7
        with:
          name: Validation results
          path: 'dev/validation/results'

      - name: Commit updated plots
        if: ${{ inputs.commit }}
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dev/validation/results/*.png'
          message: 'Update validation plots'
